plugins { id 'com.android.application' }

android {
    namespace 'com.local.noti_filter'
    compileSdk 36
    defaultConfig {
        applicationId 'com.local.noti_filter'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '1.0.3'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}

dependencies { testImplementation 'junit:junit:4.13.2' }
